name: GetAppMetadata
on:
   workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/microsoft-store-apppublisher@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - name: Get Metadata
      shell: pwsh
      run: |
            $PSVersionTable
            msstore --version
            msstore submission get f16b20ce-f82e-4046-bd70-81e703ca6e30
            msstore submission get 454ad58e-bb9a-4c56-a88c-c08011a1ead3
            msstore submission get 0eea0e40-e7a3-4fe3-abb1-199ece696151
            msstore submission get 9NP0T3QQXL70
            msstore submission get 9N508QGFDRFC
            msstore submission get 9NDRMZKRHKG3
            msstore submission get 9NV4GS32KHG2
            msstore submission status f16b20ce-f82e-4046-bd70-81e703ca6e30
            msstore submission status 454ad58e-bb9a-4c56-a88c-c08011a1ead3
            msstore submission status 0eea0e40-e7a3-4fe3-abb1-199ece696151
            msstore submission status 9NP0T3QQXL70
            msstore submission status 9N508QGFDRFC
            msstore submission status 9NDRMZKRHKG3
            msstore submission status 9NV4GS32KHG2
