name: MSIXAppMetadataUpdate
on:   
      workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/microsoft-store-apppublisher@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - run: msstore submission delete 9NP0T3QQXL70
    - name: Update metadata 
      run: |
          $metadata = Get-Content -Raw "${{ github.workspace }}/metadata/9NP0T3QQXL70.json" 
          msstore submission updateMetadata 9NP0T3QQXL70 $metadata -v
 
    - name: Publish to Store 
      run: |
         msstore submission publish 9NP0T3QQXL70 -v
         
